from __future__ import annotations

import math


ACCOUNTS = [
    {
        "id": "acc-demo",
        "label": "Demo Account",
        "type": "Demo",
        "broker": "IC Markets Demo",
        "server": "ICMarkets-Demo04",
        "masked": ".... 4821",
        "balance": 10250.0,
        "equity": 10184.3,
        "free_margin": 9810.4,
        "margin_level": 842,
        "floating_pnl": -65.7,
        "daily_pnl": 184.3,
        "latency_ms": 38,
    },
    {
        "id": "acc-prop",
        "label": "Prop Firm Account",
        "type": "Prop",
        "broker": "FTMO",
        "server": "FTMO-Server2",
        "masked": ".... 7710",
        "balance": 99875.0,
        "equity": 100412.6,
        "free_margin": 92140.0,
        "margin_level": 612,
        "floating_pnl": 537.6,
        "daily_pnl": 412.1,
        "latency_ms": 52,
    },
    {
        "id": "acc-live",
        "label": "Personal Live Account",
        "type": "Live",
        "broker": "IC Markets",
        "server": "ICMarkets-Live18",
        "masked": ".... 9032",
        "balance": 24550.0,
        "equity": 24382.1,
        "free_margin": 22110.0,
        "margin_level": 488,
        "floating_pnl": -167.9,
        "daily_pnl": -212.4,
        "latency_ms": 41,
    },
    {
        "id": "acc-research",
        "label": "Research Account",
        "type": "Research",
        "broker": "Darwinex",
        "server": "Darwinex-Demo",
        "masked": ".... 1144",
        "balance": 50000.0,
        "equity": 50122.5,
        "free_margin": 49880.0,
        "margin_level": 1240,
        "floating_pnl": 122.5,
        "daily_pnl": 88.2,
        "latency_ms": 65,
    },
]


AGENTS = [
    {
        "id": "ag-xau",
        "name": "XAUUSD PPO Scalper",
        "symbol": "XAUUSD",
        "timeframe": "M5",
        "model": "PPO-v12",
        "status": "Running",
        "action": "Hold",
        "confidence": 0.72,
        "regime": "High Volatility",
        "reward": 0.82,
        "session_reward": 14.6,
        "trades_today": 18,
        "daily_pnl": 126.4,
        "drawdown": 0.018,
        "latency_ms": 42,
        "updated_at": "12:42:18",
    },
    {
        "id": "ag-eur",
        "name": "EURUSD Trend Agent",
        "symbol": "EURUSD",
        "timeframe": "H1",
        "model": "Transformer-v4",
        "status": "Running",
        "action": "Buy",
        "confidence": 0.66,
        "regime": "Trending",
        "reward": 0.41,
        "session_reward": 6.2,
        "trades_today": 4,
        "daily_pnl": 58.2,
        "drawdown": 0.009,
        "latency_ms": 88,
        "updated_at": "12:41:55",
    },
    {
        "id": "ag-btc",
        "name": "BTCUSD Volatility Agent",
        "symbol": "BTCUSD",
        "timeframe": "M15",
        "model": "SAC-v7",
        "status": "Paused",
        "action": "Hold",
        "confidence": 0.51,
        "regime": "Choppy",
        "reward": -0.08,
        "session_reward": -2.1,
        "trades_today": 11,
        "daily_pnl": -42.5,
        "drawdown": 0.031,
        "latency_ms": 110,
        "updated_at": "12:30:02",
    },
    {
        "id": "ag-risk",
        "name": "Portfolio Risk Agent",
        "symbol": "PORTFOLIO",
        "timeframe": "-",
        "model": "XGBoost-v6",
        "status": "Running",
        "action": "Hold",
        "confidence": 0.88,
        "regime": "Elevated",
        "reward": 0.0,
        "session_reward": 0.0,
        "trades_today": 0,
        "daily_pnl": 0.0,
        "drawdown": 0.0,
        "latency_ms": 22,
        "updated_at": "12:42:20",
    },
    {
        "id": "ag-news",
        "name": "News Filter Agent",
        "symbol": "NEWS",
        "timeframe": "-",
        "model": "LSTM-v8",
        "status": "Waiting",
        "action": "Hold",
        "confidence": 0.6,
        "regime": "Pre-news",
        "reward": 0.0,
        "session_reward": 0.0,
        "trades_today": 0,
        "daily_pnl": 0.0,
        "drawdown": 0.0,
        "latency_ms": 31,
        "updated_at": "12:42:11",
    },
]


POSITIONS = [
    {
        "ticket": "#10293841",
        "symbol": "XAUUSD",
        "side": "Buy",
        "volume": 0.05,
        "entry": 2334.2,
        "current": 2336.1,
        "sl": 2329.5,
        "tp": 2342.8,
        "pnl": 9.5,
        "swap": -0.2,
        "commission": -0.35,
        "duration_min": 24,
        "strategy": "PPO Gold Scalper",
        "agent": "XAUUSD PPO Scalper",
        "confidence": 0.78,
        "risk_pct": 0.25,
        "status": "AI",
    },
    {
        "ticket": "#10293855",
        "symbol": "EURUSD",
        "side": "Buy",
        "volume": 0.20,
        "entry": 1.0842,
        "current": 1.0848,
        "sl": 1.0815,
        "tp": 1.0905,
        "pnl": 12.0,
        "swap": 0.0,
        "commission": -0.80,
        "duration_min": 142,
        "strategy": "EU Trend",
        "agent": "EURUSD Trend Agent",
        "confidence": 0.66,
        "risk_pct": 0.5,
        "status": "AI",
    },
    {
        "ticket": "#10293901",
        "symbol": "BTCUSD",
        "side": "Sell",
        "volume": 0.02,
        "entry": 67320,
        "current": 67890,
        "sl": 68100,
        "tp": 65800,
        "pnl": -114.0,
        "swap": -1.1,
        "commission": -0.40,
        "duration_min": 58,
        "strategy": "Vol Mean-Revert",
        "agent": "BTCUSD Volatility Agent",
        "confidence": 0.54,
        "risk_pct": 0.4,
        "status": "Managed",
    },
    {
        "ticket": "#10293945",
        "symbol": "USDJPY",
        "side": "Buy",
        "volume": 0.10,
        "entry": 157.21,
        "current": 157.42,
        "sl": 156.80,
        "tp": 158.10,
        "pnl": 13.4,
        "swap": 0.3,
        "commission": -0.40,
        "duration_min": 12,
        "strategy": "Manual",
        "agent": "-",
        "confidence": None,
        "risk_pct": 0.3,
        "status": "Manual",
    },
]


RISK_METRICS = [
    {"label": "Daily Loss", "value": -212.4, "max": -500, "warn": -300, "critical": -450, "unit": "USD"},
    {"label": "Current Drawdown", "value": 1.8, "max": 5, "warn": 3, "critical": 4.5, "unit": "%"},
    {"label": "Max Drawdown", "value": 4.2, "max": 8, "warn": 5, "critical": 7, "unit": "%"},
    {"label": "Risk Per Trade", "value": 0.5, "max": 1, "warn": 0.75, "critical": 0.9, "unit": "%"},
    {"label": "Total Open Risk", "value": 1.4, "max": 3, "warn": 2.2, "critical": 2.8, "unit": "%"},
    {"label": "Margin Usage", "value": 8.4, "max": 50, "warn": 30, "critical": 45, "unit": "%"},
    {"label": "Consecutive Losses", "value": 2, "max": 5, "warn": 3, "critical": 4},
    {"label": "Spread Anomaly", "value": 2.1, "max": 4, "warn": 2.5, "critical": 3.5, "unit": "x"},
]


MODELS = [
    {"id": "ppo12", "name": "PPO-v12", "algorithm": "PPO", "version": "12.3", "trained": "2026-06-10", "status": "Live", "steps": 4200000, "validation_score": 1.82, "backtest_sharpe": 2.14, "max_dd": 6.8, "live_sharpe": 1.71, "live_dd": 4.2, "drift": 0.12, "last_retrain": "2d ago"},
    {"id": "sac7", "name": "SAC-v7", "algorithm": "SAC", "version": "7.1", "trained": "2026-06-08", "status": "Paused", "steps": 3100000, "validation_score": 1.41, "backtest_sharpe": 1.62, "max_dd": 9.1, "live_sharpe": 0.88, "live_dd": 6.7, "drift": 0.42, "last_retrain": "4d ago"},
    {"id": "dqn4", "name": "DQN-v4", "algorithm": "DQN", "version": "4.0", "trained": "2026-05-29", "status": "Deprecated", "steps": 2400000, "validation_score": 1.10, "backtest_sharpe": 1.21, "max_dd": 12.4, "live_sharpe": 0.42, "live_dd": 8.9, "drift": 0.61, "last_retrain": "18d ago"},
    {"id": "tr4", "name": "Transformer-v4", "algorithm": "Transformer", "version": "4.2", "trained": "2026-06-12", "status": "Live", "steps": 6800000, "validation_score": 1.95, "backtest_sharpe": 2.04, "max_dd": 5.9, "live_sharpe": 1.62, "live_dd": 3.8, "drift": 0.18, "last_retrain": "1d ago"},
    {"id": "lstm8", "name": "LSTM-v8", "algorithm": "LSTM", "version": "8.0", "trained": "2026-06-11", "status": "Paper Trading", "steps": 5200000, "validation_score": 1.55, "backtest_sharpe": 1.74, "max_dd": 7.2, "live_sharpe": None, "live_dd": None, "drift": 0.21, "last_retrain": "1d ago"},
    {"id": "xgb6", "name": "XGBoost-v6", "algorithm": "XGBoost", "version": "6.4", "trained": "2026-06-09", "status": "Approved", "steps": 0, "validation_score": 1.30, "backtest_sharpe": 1.40, "max_dd": 8.0, "live_sharpe": None, "live_dd": None, "drift": 0.15, "last_retrain": "3d ago"},
    {"id": "ens3", "name": "Ensemble-v3", "algorithm": "Ensemble", "version": "3.1", "trained": "2026-06-13", "status": "Validating", "steps": 0, "validation_score": 2.02, "backtest_sharpe": 2.21, "max_dd": 5.5, "live_sharpe": None, "live_dd": None, "drift": 0.08, "last_retrain": "12h ago"},
]


ALERTS = [
    {"id": "a1", "severity": "High", "source": "Risk", "account": "Personal Live", "agent": "Portfolio Risk", "symbol": "-", "time": "12:41", "message": "Daily loss approaching warn threshold (-212 / -300 USD)", "status": "Open"},
    {"id": "a2", "severity": "Medium", "source": "Market", "account": "-", "agent": "-", "symbol": "XAUUSD", "time": "12:36", "message": "Spread anomaly: 2.1x normal (4.2pt)", "status": "Open"},
    {"id": "a3", "severity": "Critical", "source": "Model", "account": "-", "agent": "SAC-v7", "symbol": "BTCUSD", "time": "12:30", "message": "Model drift score 0.42 > threshold 0.40 - agent paused", "status": "Ack"},
    {"id": "a4", "severity": "Info", "source": "Discord", "account": "Demo", "agent": "-", "symbol": "XAUUSD", "time": "12:35", "message": "Command pending approval: close_half xauusd", "status": "Open"},
    {"id": "a5", "severity": "Low", "source": "System", "account": "-", "agent": "-", "symbol": "-", "time": "12:12", "message": "MT5 reconnect succeeded (latency 38ms)", "status": "Resolved"},
]


AUDIT_LOG = [
    {"timestamp": "12:42:18.412", "user": "AI-Engine", "source": "PPO-v12", "account": "acc-demo", "action": "SIGNAL_GENERATED HOLD", "result": "OK", "correlation_id": "c-9a12", "latency_ms": 42},
    {"timestamp": "12:41:50.110", "user": "Risk", "source": "RiskEngine", "account": "acc-live", "action": "ORDER_BLOCKED margin_level", "previous": "148%", "next": "114%", "result": "REJECTED", "correlation_id": "c-9a11", "latency_ms": 8},
    {"timestamp": "12:39:22.005", "user": "alex@quantai", "source": "Web", "account": "acc-prop", "action": "SL_MOVED", "previous": "2329.50", "next": "2333.00", "result": "OK", "correlation_id": "c-9a09", "latency_ms": 120},
    {"timestamp": "12:35:11.880", "user": "Discord/op_kai", "source": "Discord", "account": "acc-demo", "action": "CMD close_half xauusd", "result": "PENDING", "correlation_id": "c-9a08", "latency_ms": 0},
    {"timestamp": "12:31:00.301", "user": "AI-Engine", "source": "SAC-v7", "account": "acc-demo", "action": "AGENT_PAUSED drift>0.4", "result": "OK", "correlation_id": "c-9a06", "latency_ms": 15},
]


def equity_curve() -> list[dict[str, float | str]]:
    points = []
    for i in range(90):
        base = 10000 + i * 4
        noise = math.sin(i / 4) * 90 + math.cos(i / 7) * 60 + math.sin(i * 1.3) * 40
        equity = base + noise + (-120 if i > 60 else 0)
        points.append({"label": f"D{i + 1}", "equity": round(equity, 2), "drawdown": round(min(0, noise - 80), 2)})
    return points

